blank_issues_enabled: false
contact_links:
  - name: 🤔 Help & Questions
    url: https://community.auth0.com/c/sdks/5
    about: Ask general support or usage questions in the Auth0 Community forums
  - name: 📖 SDK API Documentation
    url: https://pkg.go.dev/github.com/auth0/go-jwt-middleware/v2
    about: Read the API documentation for this SDK
